--Initial Exploratory Data Analysis(EDA)


--total numbers of orders
SELECT
	COUNT(ORDER_ID)
FROM
	ORDERS;

--distribution of order statuses
SELECT
	ORDER_STATUS,
	COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM
	ORDERS
GROUP BY
	ORDER_STATUS
ORDER BY
	TOTAL_ORDERS;

--distribution of order by year and month
SELECT
	EXTRACT(
		YEAR
		FROM
			ORDER_PURCHASE_TIMESTAMP
	) AS ORDER_YEAR,
	EXTRACT(
		MONTH
		FROM
			ORDER_PURCHASE_TIMESTAMP
	) AS ORDER_MONTH,
	COUNT(ORDER_ID)
FROM
	ORDERS
GROUP BY
	ORDER_YEAR,
	ORDER_MONTH
ORDER BY
	ORDER_YEAR,
	ORDER_MONTH;

--unique product categories
SELECT DISTINCT
	(PRODUCT_CATEGORY_NAME)
FROM
	PRODUCTS;

-- top 10 product categories with the most products
SELECT
	PRODUCT_CATEGORY_NAME,
	COUNT(PRODUCT_ID) AS NUMBER_OF_PRODUCTS
FROM
	PRODUCTS
GROUP BY
	PRODUCT_CATEGORY_NAME
ORDER BY
	NUMBER_OF_PRODUCTS DESC
LIMIT
	10
