-- GOAL: Calculate the month-over-month (MoM) revenue growth percentage.


-- This CTE calculates the total monthly sales from delivered orders.
WITH
	MONTHLY_SALES AS (
		SELECT
			DATE_TRUNC('month', O.ORDER_PURCHASE_TIMESTAMP)::DATE AS SALES_MONTH,
			SUM(P.PAYMENT_VALUE) AS TOTAL_REVENUE
		FROM
			ORDERS O
			JOIN ORDER_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
		WHERE
			O.ORDER_STATUS = 'delivered'
		GROUP BY
			SALES_MONTH
	)
SELECT
	SALES_MONTH,
	TOTAL_REVENUE,
	LAG(TOTAL_REVENUE, 1) OVER (
		ORDER BY
			SALES_MONTH
	) AS PREVIOUS_MONTH_REVENUE,
	ROUND(
		(
			TOTAL_REVENUE - LAG(TOTAL_REVENUE, 1) OVER (
				ORDER BY
					SALES_MONTH
			)
		) / LAG(TOTAL_REVENUE, 1) OVER (
			ORDER BY
				SALES_MONTH
		) * 100,
		2
	) AS GROWTH_PERCENTAGE
FROM
	MONTHLY_SALES
ORDER BY
	SALES_MONTH;

-- GOAL: Identify the top 10 product categories by total revenue to inform business strategy.
-- This helps the business focus marketing and inventory on its most profitable items.
SELECT
	P.PRODUCT_CATEGORY_NAME AS PRODUCT_CATEGORIES,
	PT.PRODUCT_CATEGORY_NAME_ENGLISH AS ENGLISH_NAME,
	SUM(O.PRICE) AS REVENUE
FROM
	PRODUCTS P
	JOIN ORDER_ITEMS O ON P.PRODUCT_ID = O.PRODUCT_ID
	JOIN PRODUCT_CATEGORY_NAME_TRANSLATION PT ON P.PRODUCT_CATEGORY_NAME = PT.PRODUCT_CATEGORY_NAME
GROUP BY
	PRODUCT_CATEGORIES,
	ENGLISH_NAME
ORDER BY
	REVENUE DESC
LIMIT
	10;
