-- GOAL: Identify the top 10 states of Brazil by order volume to understand key geographical markets.
SELECT
    c.customer_state,
    COUNT(o.order_id) AS number_of_orders
FROM
    customers c
JOIN
    orders o ON c.customer_id = o.customer_id
GROUP BY
    c.customer_state
ORDER BY
    number_of_orders DESC
LIMIT 10;

-- GOAL: Analyze the usage and revenue generated by different payment methods.
-- This helps in understanding customer preferences for payments.
SELECT
    payment_type,
    COUNT(*) AS number_of_orders,
    ROUND(AVG(payment_installments), 2) AS avg_installments,
    SUM(payment_value) AS total_revenue
FROM
    order_payments
GROUP BY
    payment_type
ORDER BY
    total_revenue DESC;